---
  INFO:
    JEDNOSTKAREJESTROWA: 129127_7 Zielonki
    OBREB:
    KERG:
    GMLFILE:
  SETTINGS:
    PODZIAL: False
    MDCP: True
    INWENTARYZACJA: False
    USTALENIE: False
    ROZGRANICZENIE: False